### PR TITLE
Remove lodash

### PR DESCRIPTION
**Pull request by Cryrivers**
### Description
As functions imported from Lodash have been already supported by either ECMAScript 5 or Ember framework, this PR removes Lodash to reduce the addon's size.

### CODE REVIEW

**Comment by Cryrivers** [comment]
I signed it!

**Comment by Cryrivers** [comment]
Not sure what happened to Travis CI but I passed all test cases on my local machine.

**Comment by tsubik** [comment]
Yeah, looks like something got flaky. I've run tests locally for your branch, and all looks fine :+1:

**Comment by mileszim** [comment]
Lodash is giving the same deprecation warnings of Torii. Is it possible to fast-track this PR?

**Comment by jamesdaniels** [comment]
I'm kicking this now with the switch to yarn, hopefully that helps the CI failures.

**Comment by jamesdaniels** [comment]
Ack @Cryrivers, mind giving the failing tests a look now that we've locked it down with yarn?

**Comment by Cryrivers** [comment]
Will do

**Comment by Cryrivers** [comment]
image

@jamesdaniels Any idea why all test cases can pass on my local machine but not Travis CI?

**Comment by mileszim** [comment]
@Cryrivers I'm gonna take a gander it has to do with cached node_modules https://travis-ci.org/firebase/emberfire/jobs/239540498/config

**Comment by Cryrivers** [comment]
@mileszim tried with no luck 😢

**Comment by ibroadfo** [comment]
I tried correctly disabling caching by setting `cache: false` but the build still failed: https://travis-ci.org/ibroadfo/emberfire/jobs/241577735

**Comment by ibroadfo** [comment]
Ah! it's because travis is using Firefox 31. I'm not sure exactly what code is causing the problem though.

**Comment by ibroadfo** [comment]
I've submitted a PR that fixes the Firefox issue https://github.com/firebase/emberfire/pull/516 and merged it into my copy of this lodash PR to check that it works, which it does! https://travis-ci.org/ibroadfo/emberfire/jobs/241726167 :)

**Comment by jamesdaniels** [comment]
Thanks!

**Comment by mileszim** [comment]
nice work! thanks for getting this in!

**Pull request merged**
