### PR TITLE
Add test waiters to adapter

### LINKED ISSUE #312: Error Running Acceptance Tests
Hello there,

I'm trying emberfire out, but I've run into a problem: I get an error every time I run an acceptance test. I'e pasted the error below. Any ideas?

Thank you!

`FIREBASE WARNING: Exception was thrown by user callback. Error: Called stop() outside of a test context
    at Object.extend.stop (http://localhost:4200/assets/test-support.js:3000:10)
    at exports.default._emberTestingAdaptersAdapter.default.extend.asyncStart (http://localhost:4200/assets/vendor.js:52454:13)
    at asyncStart (http://localhost:4200/assets/vendor.js:43110:47)
    at Object.async (http://localhost:4200/assets/vendor.js:43124:7)
    at fulfill (http://localhost:4200/assets/vendor.js:66638:22)
    at handleMaybeThenable (http://localhost:4200/assets/vendor.js:66598:9)
    at resolve (http://localhost:4200/assets/vendor.js:66611:7)
    at resolvePromise (http://localhost:4200/assets/vendor.js:66755:9)
    at http://localhost:4200/assets/vendor.js:99926:11
    at ns.wrapper.fb.api.Query.goog.defineClass.once.onceCallback (http://localhost:4200/assets/vendor.js:99115:43) 
firebase-debug.js:4798 Uncaught Error: Called stop() outside of a test contextextend.stop @ qunit.js:329exports.default._emberTestingAdaptersAdapter.default.extend.asyncStart @ ember.debug.js:41900asyncStart @ ember.debug.js:32556(anonymous function) @ ember.debug.js:32570fulfill @ ember.debug.js:56084handleMaybeThenable @ ember.debug.js:56044resolve @ ember.debug.js:56057resolvePromise @ ember.debug.js:56201(anonymous function) @ firebase.js:193ns.wrapper.fb.api.Query.goog.defineClass.once.onceCallback @ firebase-debug.js:12452ns.wrapper.fb.core.view.ValueEventRegistration.getEventRunner @ firebase-debug.js:5053ns.wrapper.fb.core.util.exceptionGuard @ firebase-debug.js:4793ns.wrapper.fb.core.view.EventList.raise @ firebase-debug.js:3407ns.wrapper.fb.core.view.EventQueue.raiseQueuedEventsMatchingPredicate_ @ firebase-debug.js:3379ns.wrapper.fb.core.view.EventQueue.raiseEventsForChangedPath @ firebase-debug.js:3367(anonymous function) @ firebase-debug.js:11666(anonymous function) @ firebase-debug.js:11094ns.wrapper.fb.core.PersistentConnection.goog.defineClass.onDataMessage_ @ firebase-debug.js:11250ns.wrapper.fb.realtime.Connection.onDataMessage_ @ firebase-debug.js:10821ns.wrapper.fb.realtime.Connection.onPrimaryMessageReceived_ @ firebase-debug.js:10815ns.wrapper.fb.realtime.Connection.connReceiver_ @ firebase-debug.js:10731ns.wrapper.fb.realtime.WebSocketConnection.appendFrame_ @ firebase-debug.js:10507ns.wrapper.fb.realtime.WebSocketConnection.handleIncomingFrame @ firebase-debug.js:10539ns.wrapper.fb.realtime.WebSocketConnection.open.mySock.onmessage @ firebase-debug.js:10464`

`
Uncaught Error: Called stop() outside of a test contextextend.stop @ qunit.js:329exports.default._emberTestingAdaptersAdapter.default.extend.asyncStart @ ember.debug.js:41900asyncStart @ ember.debug.js:32556(anonymous function) @ ember.debug.js:32570fulfill @ ember.debug.js:56084handleMaybeThenable @ ember.debug.js:56044resolve @ ember.debug.js:56057resolvePromise @ ember.debug.js:56201(anonymous function) @ firebase.js:193ns.wrapper.fb.api.Query.goog.defineClass.once.onceCallback @ firebase-debug.js:12452ns.wrapper.fb.core.view.ValueEventRegistration.getEventRunner @ firebase-debug.js:5053ns.wrapper.fb.core.util.exceptionGuard @ firebase-debug.js:4793ns.wrapper.fb.core.view.EventList.raise @ firebase-debug.js:3407ns.wrapper.fb.core.view.EventQueue.raiseQueuedEventsMatchingPredicate_ @ firebase-debug.js:3379ns.wrapper.fb.core.view.EventQueue.raiseEventsForChangedPath @ firebase-debug.js:3367(anonymous function) @ firebase-debug.js:11666(anonymous function) @ firebase-debug.js:11094ns.wrapper.fb.core.PersistentConnection.goog.defineClass.onDataMessage_ @ firebase-debug.js:11250ns.wrapper.fb.realtime.Connection.onDataMessage_ @ firebase-debug.js:10821ns.wrapper.fb.realtime.Connection.onPrimaryMessageReceived_ @ firebase-debug.js:10815ns.wrapper.fb.realtime.Connection.connReceiver_ @ firebase-debug.js:10731ns.wrapper.fb.realtime.WebSocketConnection.appendFrame_ @ firebase-debug.js:10507ns.wrapper.fb.realtime.WebSocketConnection.handleIncomingFrame @ firebase-debug.js:10539ns.wrapper.fb.realtime.WebSocketConnection.open.mySock.onmessage @ firebase-debug.js:10464
`

### PR DESCRIPTION
**Pull request by tstirrat**
Adds test waiters to the adapter for model requests.

Relationships are not seeming to resolve correctly. need more tests.

Still needs:

- [x] Auth waiters integrated from #330 (in progress)
- [x] More tests, incl torii auth tests

/cc @gabrielgrant @mtmckenna @edborden

Fixes #312

### CODE REVIEW

**Comment by tstirrat** [comment]
@edborden can you confirm if this fixes all of your issues with acceptance tests?

**Comment by edborden** [comment]
@tstirrat This a huge improvement!  `store#query` is still tripping me up, though.

**Comment by tstirrat** [comment]
@edborden thanks for the update!

I'll merge this, but you'll need to give me some more info on the "tripping up", because my query related acceptance tests seem to be working.

**Comment by edborden** [comment]
@tstirrat You're right, I think I'm all good. There are some places where my test helpers function a bit differently than yours, so I had some cleaning to do. I want to go back through when I get a chance soon and put some work into the helpers on the addon side then abstract them out so we can all work toward being somewhat consistent in testing methodology. Thanks for this!

**Pull request merged**
