### PR TITLE
Get `include: 'somerel'` working

### LINKED ISSUE #617: Using `include` in findRecord throws error
Having issues using `include` with the following request:

```js
this.store.findRecord('idea', ideaId, { include: 'outline' })
    });
```

Screen Shot 2020-06-24 at 4 56 41 PM

> firestore.js:312 Uncaught (in promise) TypeError: Cannot set property '_included' of undefined
    at firestore.js:312

And the model of `idea`:

```js
import Model, { attr, belongsTo, hasMany } from '@ember-data/model';
import Blog from './blog';
import OutlineItem from './outline-item';

export default class Idea extends Model {
  @attr('string') title!: string;
  @attr('string') description!: string;
  @attr('date') createdAt!: Date;
  @attr('date') updatedAt!: Date;

  @hasMany('outline-item', { subcollection: true } as any) outline!: Promise<
    OutlineItem[]
  >;
  @belongsTo('blog') blog!: Promise<Blog>;
}
```

Tried removing subcollection too, same issue.

### PR DESCRIPTION
**Pull request by knownasilya**
closes #617

### CODE REVIEW

**Comment by knownasilya** [comment]
@googlebot I signed it!

**Comment by knownasilya** [comment]
Combined with this change:

```js
updateRecord(_store, type, snapshot) {
        const id = snapshot.id;
        const data = this.serialize(snapshot, { includeId: false });
        // TODO is this correct? e.g, clear dirty state and trigger didChange; what about failure?
        let docRef;

        return docReference(this, type, id)
          .then(doc => {
            docRef = doc;
            return doc.update(data);
          })
          .then(() => {
            let rels = Array.from(type.relationshipsByName.values());
            let subcollections = rels.filter(rel => rel.meta.kind === 'hasMany' && rel.meta.options && rel.meta.options.subcollection);

            let updates = subcollections.reduce((all, rel) => {
              let snapshots = snapshot.hasMany(rel.meta.key);
              let collectionName = collectionNameForType(rel.type);

              snapshots.forEach(snap => {
                let hasChanges = Object.keys(snap.changedAttributes());

                if (!hasChanges) {
                  return;
                }

                let ref = snap.id ? docRef.collection(collectionName).doc(snap.id) : docRef.collection(collectionName).doc();

                all.push(
                  ref.set(this.serialize(snap, { includeId: false }))
                );
              })

              return all;
            }, [])

            return Promise.all(updates);
          })
    }
```

I got subcollections writing, but get a weird error after save:

> "Error: The adapter could not find the resource
    at ErrorClass.AdapterError (http://localhost:4200/assets/vendor.js:77044:29)
    at new ErrorClass (http://localhost:4200/assets/vendor.js:77077:24)
    at ApplicationSerializer.normalizeSingleResponse (http://localhost:4200/assets/vendor.js:120087:15)
    at ApplicationSerializer.normalizeSaveResponse (http://localhost:4200/assets/vendor.js:87587:19)
    at ApplicationSerializer.normalizeUpdateRecordResponse (http://localhost:4200/assets/vendor.js:87573:19)
    at ApplicationSerializer.normalizeResponse (http://localhost:4200/assets/vendor.js:87432:23)
    at normalizeResponseHelper (http://localhost:4200/assets/vendor.js:90888:41)
    at http://localhost:4200/assets/vendor.js:99088:21
    at Backburner._run (http://localhost:4200/assets/vendor.js:57641:25)
    at Backburner._join (http://localhost:4200/assets/vendor.js:57617:21)"

**Comment by knownasilya** [comment]
@runspired For some reason I get a error about enabling a feature flag when i tried using `snapshot.isNew`, any workarounds?

**Comment by knownasilya** [comment]
@jamesdaniels This fix should be ready. I'll submit the subcollections in a new PR.

**Comment by KMontag42** [comment]
would love to see this merged :)

**Comment by runspired** [comment]
@knownasilya looks like an error this project is throwing and not data on that trace. As for feature flag error that’s surprising could you give me the trace for that?

**Comment by knownasilya** [comment]
This project seems abandoned, maybe time to fork to adopted-ember-addons org?

**Review by jamesdaniels — APPROVED** [review]
LGTM, thanks. Sorry for the radio silence, going to dust things off again shortly.

**Pull request merged**
