### PR TITLE
multipath save 

### PR DESCRIPTION
**Pull request by olivierchatry**
Test are not passing, because I think they are not valid in the way we want this thing to work : 

To destroy a link you need to set null to it, and some of the tests are just emptying the relation object.

For example :

``` javascript
// comments is a hasMany
comments:{id1:true,id2:true}
// test want to reset comment and check if it was emptied
comments:{}
```

Cannot work, at it will either require comment to be set to null : 

``` javascript
comments:null
```

Or all elements to be set to null:

``` javascript
comments:{id1:null,id2:null}
```

The other problem, which I'm not sure I can trace back ( lacking time ) is this error :

> Error: Firebase.update failed: First argument  contains an invalid key (children/- KAJmTkzssePlP9HbfSs) in property 'blogs.tests.adapter.updaterecord.embedded.treeNodes.-KAJmTkyP_fKXLpXTw47.children.-KAJmTkyP_fKXLpXTw48'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]" (http://localhost:7357/assets/vendor.js:71731)

I think it is "internal" checking. 

As an example here is what the multipath code generate from the usual serializedRecord :

``` javascript
// BEFORE ======> 
{
    "label": "Parent Node",
    "created": null,
    "children": {
        "-KAJmTkyP_fKXLpXTw48": {
            "id": "-KAJmTkyP_fKXLpXTw48",
            "label": "Child Node",
            "created": null,
            "children": {
                "-KAJmTkzssePlP9HbfSs": {
                    "id": "-KAJmTkzssePlP9HbfSs",
                    "label": "Child Sub Node",
                    "created": null,
                    "children": null,
                    "config": null
                }
            },
            "config": null
        }
    },
    "config": null
}
// AFTER ======> 
{
    "label": "Parent Node",
    "created": null,
    "config": null,
    "children/-KAJmTkyP_fKXLpXTw48": {
        "id": "-KAJmTkyP_fKXLpXTw48",
        "label": "Child Node",
        "created": null,
        "config": null,
        "children/-KAJmTkzssePlP9HbfSs": {
            "id": "-KAJmTkzssePlP9HbfSs",
            "label": "Child Sub Node",
            "created": null,
            "children": null,
            "config": null
        }
    }
}
```

### CODE REVIEW

**Comment by olivierchatry** [comment]
( I added output of "BEFORE / AFTER" in the test for debugging purpose )

**Comment by olivierchatry** [comment]
@tstirrat I'm really not sure if it is the way to go. I'm saving the previously serialized object to be able to do the diff when updating, but this also needs to be maintained accross the different update ( which anyway happen only in _handleChildUpdate ). Feedback would be appreciated, if you know a better way.

There is also one test ( last one ) failing. I'm not sure what is the message is about.

At the very least the serialisation seems to be OK.

**Comment by olivierchatry** [comment]
well, seems like I screwed the commit, I will push again on monday.

**Comment by olivierchatry** [comment]
So, for my project ( which is not using embedded record ) everything works super fine.

But, the last test is failing, which is using embedded record. 

> Error: Firebase.update failed: First argument contains a path /children/-KAZcuPNcbNIVw0aul7- that is ancestor of another path /children/-KAZcuPNcbNIVw0aul7-/children/-KAZcuPNcbNIVw0aul70 (http://localhost:7357/assets/vendor.js:71762)

The errror is explicit, I'm not sure there is away to fix that, except doing multiple update in this particular case. Any thought @tstirrat ?

**Comment by olivierchatry** [comment]
@tstirrat ping.

**Comment by tstirrat** [comment]
@jamesdaniels and I are going to revisit this next week.

**Pull request closed without merging**
