### PR TITLE
Wait for _updateRecord in tests

### PR DESCRIPTION
**Pull request by tstirrat**
### Description

Adds Ember test waiting to the adapter's `_updateRecord` so that tests will wait while saving and updating records. Previously we were only waiting while fetching and querying records.

#404

### CODE REVIEW

**Comment by gabrielgrant** [comment]
Sweet! :+1: 

Looks like this should cover all the cases where I've been still relying on the hack of using a timed test waiter to check model state, right? Or are there still some known cases that aren't covered? 

I'm assuming there's nothing that waits for direct FB writes (eg for transactions), rigth? but checking model state doesn't help with that anyway

**Comment by tstirrat** [comment]
Direct FB writes would be hard to wait for, we know when they are complete because the `value` event fires, but we don't know when they started (because it happens outside of Ember).

**Comment by tstirrat** [comment]
I think for testing direct writes you'd need to ask the test to wait for the write to return using an async helper. Here's some examples: http://stackoverflow.com/questions/26498845/using-ember-cli-how-do-i-get-an-acceptance-test-to-wait-for-a-promise

**Comment by villander** [comment]
@tstirrat `async helper` not working too. I will try this

**Comment by villander** [comment]
@tstirrat this still not working using 2.0.4 version. You can reopen this issue?

**Pull request merged**
