### PR TITLE
wrap firebase auth with test waiters

### LINKED ISSUE #312: Error Running Acceptance Tests
Hello there,

I'm trying emberfire out, but I've run into a problem: I get an error every time I run an acceptance test. I'e pasted the error below. Any ideas?

Thank you!

`FIREBASE WARNING: Exception was thrown by user callback. Error: Called stop() outside of a test context
    at Object.extend.stop (http://localhost:4200/assets/test-support.js:3000:10)
    at exports.default._emberTestingAdaptersAdapter.default.extend.asyncStart (http://localhost:4200/assets/vendor.js:52454:13)
    at asyncStart (http://localhost:4200/assets/vendor.js:43110:47)
    at Object.async (http://localhost:4200/assets/vendor.js:43124:7)
    at fulfill (http://localhost:4200/assets/vendor.js:66638:22)
    at handleMaybeThenable (http://localhost:4200/assets/vendor.js:66598:9)
    at resolve (http://localhost:4200/assets/vendor.js:66611:7)
    at resolvePromise (http://localhost:4200/assets/vendor.js:66755:9)
    at http://localhost:4200/assets/vendor.js:99926:11
    at ns.wrapper.fb.api.Query.goog.defineClass.once.onceCallback (http://localhost:4200/assets/vendor.js:99115:43) 
firebase-debug.js:4798 Uncaught Error: Called stop() outside of a test contextextend.stop @ qunit.js:329exports.default._emberTestingAdaptersAdapter.default.extend.asyncStart @ ember.debug.js:41900asyncStart @ ember.debug.js:32556(anonymous function) @ ember.debug.js:32570fulfill @ ember.debug.js:56084handleMaybeThenable @ ember.debug.js:56044resolve @ ember.debug.js:56057resolvePromise @ ember.debug.js:56201(anonymous function) @ firebase.js:193ns.wrapper.fb.api.Query.goog.defineClass.once.onceCallback @ firebase-debug.js:12452ns.wrapper.fb.core.view.ValueEventRegistration.getEventRunner @ firebase-debug.js:5053ns.wrapper.fb.core.util.exceptionGuard @ firebase-debug.js:4793ns.wrapper.fb.core.view.EventList.raise @ firebase-debug.js:3407ns.wrapper.fb.core.view.EventQueue.raiseQueuedEventsMatchingPredicate_ @ firebase-debug.js:3379ns.wrapper.fb.core.view.EventQueue.raiseEventsForChangedPath @ firebase-debug.js:3367(anonymous function) @ firebase-debug.js:11666(anonymous function) @ firebase-debug.js:11094ns.wrapper.fb.core.PersistentConnection.goog.defineClass.onDataMessage_ @ firebase-debug.js:11250ns.wrapper.fb.realtime.Connection.onDataMessage_ @ firebase-debug.js:10821ns.wrapper.fb.realtime.Connection.onPrimaryMessageReceived_ @ firebase-debug.js:10815ns.wrapper.fb.realtime.Connection.connReceiver_ @ firebase-debug.js:10731ns.wrapper.fb.realtime.WebSocketConnection.appendFrame_ @ firebase-debug.js:10507ns.wrapper.fb.realtime.WebSocketConnection.handleIncomingFrame @ firebase-debug.js:10539ns.wrapper.fb.realtime.WebSocketConnection.open.mySock.onmessage @ firebase-debug.js:10464`

`
Uncaught Error: Called stop() outside of a test contextextend.stop @ qunit.js:329exports.default._emberTestingAdaptersAdapter.default.extend.asyncStart @ ember.debug.js:41900asyncStart @ ember.debug.js:32556(anonymous function) @ ember.debug.js:32570fulfill @ ember.debug.js:56084handleMaybeThenable @ ember.debug.js:56044resolve @ ember.debug.js:56057resolvePromise @ ember.debug.js:56201(anonymous function) @ firebase.js:193ns.wrapper.fb.api.Query.goog.defineClass.once.onceCallback @ firebase-debug.js:12452ns.wrapper.fb.core.view.ValueEventRegistration.getEventRunner @ firebase-debug.js:5053ns.wrapper.fb.core.util.exceptionGuard @ firebase-debug.js:4793ns.wrapper.fb.core.view.EventList.raise @ firebase-debug.js:3407ns.wrapper.fb.core.view.EventQueue.raiseQueuedEventsMatchingPredicate_ @ firebase-debug.js:3379ns.wrapper.fb.core.view.EventQueue.raiseEventsForChangedPath @ firebase-debug.js:3367(anonymous function) @ firebase-debug.js:11666(anonymous function) @ firebase-debug.js:11094ns.wrapper.fb.core.PersistentConnection.goog.defineClass.onDataMessage_ @ firebase-debug.js:11250ns.wrapper.fb.realtime.Connection.onDataMessage_ @ firebase-debug.js:10821ns.wrapper.fb.realtime.Connection.onPrimaryMessageReceived_ @ firebase-debug.js:10815ns.wrapper.fb.realtime.Connection.connReceiver_ @ firebase-debug.js:10731ns.wrapper.fb.realtime.WebSocketConnection.appendFrame_ @ firebase-debug.js:10507ns.wrapper.fb.realtime.WebSocketConnection.handleIncomingFrame @ firebase-debug.js:10539ns.wrapper.fb.realtime.WebSocketConnection.open.mySock.onmessage @ firebase-debug.js:10464
`

### PR DESCRIPTION
**Pull request by gabrielgrant**
fixes #312

I've added the wrapper to the OAuth popup login path too, though it's not totally clear how this interacts with an ember acceptance test: running the tests in the browser seems seems to work with facebook login (so long as I've already authenticated the browser with the app manually) but I haven't thoroughly tested with other OAuth providers

### CODE REVIEW

**Comment by tstirrat** [comment]
Thanks for this, I like the idea, but think we can remove a lot of the duplication.

I wonder if we can clean this up by adding a node style to promise wrapper that also inserts the test waiters:

```js
var authCalls = 0;

// ...
promisify: function(ref, methodName, args) {
  return new Ember.RSVP.Promise((resolve, reject) => {
    if (Ember.testing) {
      Ember.Test.registerWaiter(() => authCalls === 0); 
    }
    authCalls++;
    var callback = function(error, authData) {
      authCalls--;
      if (error) { 
        reject(error);
      } else {
        resolve(authData);
      }
    };
    
    args.push(callback);
    ref[methodName].apply(args)
  });
}

// called like so
return this.promisify(this.get('firebase'), 'authWithCustomToken', [options.token]);
```

**Comment by gabrielgrant** [comment]
Hey, @tstirrat sorry for the delay in getting back to this. While my quick hack got this working for me, you're right that a promise wrapper is probably a cleaner way to go to avoid the duplication.

**Comment by tstirrat** [comment]
I'm currently in the process of adding waiters to all the model requests. So I can cover this auth stuff in that PR, too.

More than happy for you to fix up this PR in the meantime, just let me know, either way.

**Comment by tstirrat** [comment]
Closing this in favor of #344 where I will use a common mixin

**Pull request closed without merging**
