### PR TITLE
Add re-usable test helpers

### LINKED ISSUE #251: Expose testing helpers
Expose the internal testing helpers so that others may use them in integration/acceptance tests.

Something like the following should be possible:

```js
var application, mockRef;

module('Acceptance: User listing', {
  beforeEach: function() {
    application = startApp();
    mockRef = createFirebaseMockRef(MY_FIXTURE_DATA);
    overrideAdapterRef(application, mockRef, 'user');
    // this is effectively setting the adapterFor('user')._ref
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('user online status is updated', function(assert) {
  var userId = 'someuserid';
  var userRef = mockRef.child('users').child(userId);
  
  visit('/users');
  // and password
  andThen(() => {
    // test some user state is online
  });
  andThen(() => {
    return userRef.child('status').set('offline');
  });
  andThen(() => {
    // test that the user state is 'offline'
  });
});
```

### PR DESCRIPTION
**Pull request by tstirrat**
Provides:

**replaceAppRef(app, ref, [model])**

- Replaces the app's adapter with your supplied Firebase ref, defaults to replacing the `application` adapter but you could supply a model here if you have mixed adapters in your app and need to override only a certain model's adapter

You should probably use [MockFirebase](https://github.com/katowulf/mockfirebase) if you are only needing basic set/update/remove functionality. Queries will need a offline+stubbed reference.

```js
var app, ref;
beforeEach(function () {
  ref = new MockFirebase('https://some-url');
  app = startApp();
  replaceAppRef(app, ref);
});
```

**stubFirebase() / unstubFirebase()**

- Needed to stub offline refs so that set, update and remove operations fire their callbacks and complete the wrapping promises
- Only needed if you are using offline refs, you should probably use [MockFirebase](https://github.com/katowulf/mockfirebase) unless you need complex things like queries

**createOfflineRef([initialData], [url])**

- Creates a reference in offline mode with optional data. You must run `stubFirebase()` before this
- The url defaults to https://emberfire-tests.firebaseio.com unless specified

```js
stubFirebase();
var ref = createOfflineRef({
  posts: {
    post_1: {
      title: 'Title'
    }
  }
}, 'https://my-cool-app-tests.firebaseio.com');

ref.toString(); // https://my-cool-app-tests.firebaseio.com/

ref.child('posts/post_1').once('value', function(snap) {
  console.log(snap.val()); // { title: 'Title' }
});
unstubFirebase();
```

**Full Example:**

```js
import createOfflineRef from '../helpers/create-offline-ref';
import replaceAppRef from '../helpers/replace-app-ref';
import stubFirebase from '../helpers/stub-firebase';
import unstubFirebase from '../helpers/unstub-firebase';

import FIXTURE_DATA from '../helpers/fixture-data'; // defined in your local repo

describe('Acceptance: /post/:id', function() {
  var application, ref;

  beforeEach(function() {
    stubFirebase();
    application = startApp();
    ref = createOfflineRef(FIXTURE_DATA);

    replaceAppRef(application, ref);
  });

  afterEach(function() {
    unstubFirebase();
    Ember.run(application, 'destroy');
  });

  it('can visit /post/post_1', function() {
    visit('/post/post_1');
    andThen(function() {
      expect(find('.post .title').text().trim()).to.equal('Title');
    });
    andThen(function() {
      ref.child('posts/post_1/title').set('Title Updated');
    });
    andThen(function() {
      expect(find('.post .title').text().trim()).to.equal('Title Updated');
    });
  });

});
```

**Please make any suggestions if the helper names or apis can be clearer.**

Fixes #251

/cc @brancusi @aceofspades @edborden @scolyer

### CODE REVIEW

**Comment by scolyer** [comment]
This looks great @tstirrat . Exactly what I need. I am currently doing this by injecting a replacement firebase service into emberfire. It works ok but isn't as nice as this.

**Comment by tstirrat** [comment]
Should we call them `(un)stubFirebaseOffline` so that it is clear these methods are only needed if you're using the offline refs?

**Comment by tstirrat** [comment]
Some others who are interested in EmberFire testing and might want to comment on the methods suggested here:

/cc @gabrielgrant @mtmckenna @RayMangum @leifcr

**Comment by san650** [comment]
@tstirrat Thanks for working on this! It's a really needed feature. I just tried this branch on a project I have with emberfire but had the following error:

```
not ok 1 PhantomJS 1.9 - TestLoader Failures: dummy/tests/acceptance/dummy-test: could not be loaded
    ---
        actual: >
            null
        message: >
            Died on test #1     at test (http://localhost:7357/assets/test-support.js:3183)
                at http://localhost:7357/assets/test-support.js:6175
                at http://localhost:7357/assets/test-loader.js:62
                at http://localhost:7357/assets/test-loader.js:51
                at http://localhost:7357/assets/test-loader.js:82
                at http://localhost:7357/assets/test-support.js:6182: Could not find module `sinon` imported from `dummy/tests/helpers/stub-firebase`
```

I think the problem with this implementation is that it depends on `sinon` ([sinon shim](https://github.com/firebase/emberfire/blob/master/vendor/sinon/shim.js)) which is not available to end users (see [this](https://github.com/firebase/emberfire/blob/master/ember-cli-build.js#L24-L31)). Would you consider changing the implementation to avoid using `sinon`?

**Comment by tstirrat** [comment]
@san650 good catch! I will see what I can do!

**Comment by san650** [comment]
I did a quick test and removed sinon and the acceptance tests worked! You can see the changes I made here https://github.com/san650/emberfire/commit/7638f764a2a47c1f3aa5d7d30cba4e95f0ef2dd1 (quick and dirty hack :stuck_out_tongue:)

**Comment by tstirrat** [comment]
@san650 I updated this branch with 63856aa that should fix the sinon issue.

**Comment by san650** [comment]
@tstirrat Thanks for the update! 

It's still failing, I think you forgot to remove the `import sinon` statement from https://github.com/firebase/emberfire/blob/63856aa5abb73f365e19fbb16ab9d0688530f1b8/test-support/helpers/stub-firebase.js#L2

**Comment by tstirrat** [comment]
LOL, yep. will fix that.

**Comment by san650** [comment]
@tstirrat now it's working

**Comment by xymbol** [comment]
@san650 @tstirrat Awesome guys, thanks!

**Comment by gabrielgrant** [comment]
whoa, not sure how i overlooked this in my GH notifications... this is awesome @tstirrat 

After a series a frustrations with mocking/stubbing and [FirebaseServer](https://github.com/urish/firebase-server), I've ended up just using a real firebase instance for testing (by just subbing out the URL in my config). This obviously gets rid of the annoying, subtle differences between test and live environments, but requires maintaining a bunch of extra code to set/inspect state, causes multiple test instances to interfere with each other, makes the tests run super slow...and just feels wrong. So looking forward to giving this a try.

Haven't seen any docs on this...would be great to get a testing [guide](https://github.com/firebase/emberfire/blob/master/docs/guide/README.md) (in all your free time ;)

**Comment by tstirrat** [comment]
@gabrielgrant @binhums and I sat down yesterday to get a guide going on this very topic :)

**Comment by gabrielgrant** [comment]
@tstirrat awesome, looking forward to seeing it!

**Pull request merged**
