### PR TITLE
Upgrade lodash

### PR DESCRIPTION
**Pull request by ibroadfo**
### Description

The existing version of lodash is out of date and conflicts with the current version; this PR updates both ember-lodash and lodash, and passes all tests.

### CODE REVIEW

**Comment by ibroadfo** [comment]
Hmm. These commits passed for me. :( https://travis-ci.org/

**Comment by ibroadfo** [comment]
And I failed at pasting the build. Here it is: https://travis-ci.org/ibroadfo/emberfire/builds/216707054

**Comment by ibroadfo** [comment]
Ok, so: the original build failure was simply down to cached node_modules, which I should have figured out much sooner. 

Today's failure I'm 99% sure is just a random flicker, especially since it's only on 1/4 of the jobs. Could someone restart it to prove me right?

**Comment by Cryrivers** [comment]
```
import assign from 'lodash/assign';
import forEach from 'lodash/forEach';
import filter from 'lodash/filter';
import map from 'lodash/map';
import includes from 'lodash/includes';
import indexOf from 'lodash/indexOf';
import find from 'lodash/find';
```

I believe those functions have been already supported by Ember (either under `Ember.A` or `Ember` namespaces). I wonder if it is necessary to include lodash anyway. @tstirrat could you give us a reason?

**Comment by tsubik** [comment]
I agree that lodash should be removed from that repo to reduce its size. When I have time I will try to make a PR for that.

**Comment by jamesdaniels** [comment]
@tsubik we aim to support Ember LTS through to Release channel (currently `2.8.3`-`2.12.0`)

**Comment by Cryrivers** [comment]
@jamesdaniels @tsubik please see #502

**Comment by almcc** [comment]
It would be nice to see this get merged (or alternative fix) as I currently can't have both emberfire and ember-cli-mirage installed because of a lodash version issue. I have 

```json
"devDependencies": {
    ...
    "emberfire": "git+https://git@github.com/ibroadfo/emberfire.git",
    ...
  },
```
as a workaround for now to continue with development.

**Comment by Cryrivers** [comment]
See also: #502

**Comment by ibroadfo** [comment]
Thanks to whoever restarted the build! Obviously we don't want to merge the travis.yml changes, so if someone can let me know once this has been reviewed I'll checkout the earlier commit and push that. :)

**Comment by jamesdaniels** [comment]
#502 is the direction I'd rather go, if we can get it green.

**Comment by ibroadfo** [comment]
👍

**Pull request closed without merging**
