### PR TITLE
Fix #508 (`TypeError: Cannot read property 'getRecord' of null`)

### LINKED ISSUE #508: TypeError: Cannot read property 'getRecord' of null
### Version info

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.12.2
DEBUG: Ember Data : 2.12.2
DEBUG: Firebase   : 3.9.0
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 3.2.1
DEBUG: -------------------------------
```

Note that EmberFire reports as being [0.0.0](https://github.com/firebase/emberfire/commit/665bebac765a5f0cc4c60962b32197f2444ac2ff
), but 2.0.7 is installed via yarn.

```
emberfire@^2.0.7:
  version "2.0.7"
  resolved "https://registry.yarnpkg.com/emberfire/-/emberfire-2.0.7.tgz#5635e8f7515b64dd78c8096999e467dd7f5af122"
  dependencies:
    broccoli-merge-trees "^1.2.1"
    broccoli-webpack "^1.0.0"
    chalk "1.1.3"
    ember-cli-babel "5.1.6"
    ember-lodash "0.0.7"
    firebase "^3.4.1"
```

### Test case

I believe I have created an minimal, complete, and verifiable example here: https://github.com/amiel/emberfire-monkeypatch-issue. It is not in JSFiddle or Plunker as I found it  easier to get all the setup deterministic with yarn, etc using ember-cli.

### Steps to reproduce

1. `git clone https://github.com/amiel/emberfire-monkeypatch-issue.git`
2. `cd emberfire-monkeypatch-issue`
3. `yarn install`
4. `bower install`
5. `ember serve`
6. visit http://localhost:4200 and open the javascript developer console
7. Click on the "Create a comment" button

### Expected behavior

I expect to not see an exception and I expect to see:

> This is comment #1
>
> - Author #1

Expected behavior can be reproduced by following the reproduction steps in the [`without-emberfire`](https://github.com/amiel/emberfire-monkeypatch-issue/tree/without-emberfire) branch.

### Actual behavior

I see the following error in the javascript console:

```
TypeError: Cannot read property 'getRecord' of null
```

The backtrace points to [this line in the emberfire initializer](https://github.com/firebase/emberfire/blob/v2.0.7/addon/initializers/emberfire.js#L74). Following the backtrace further, this is triggered by ember-data, which pushes included records to the store after committing write operations (create/update/delete) when the response has an `included` section (see [this part of `_commit` in the ember data store](https://github.com/emberjs/data/blob/v2.12.2/addon/-private/system/store.js#L2734-L2736)).

### Resolution

One idea for resolving this could be to change ember-data to change [this line](https://github.com/emberjs/data/blob/v2.12.2/addon/-private/system/store.js#L2735):

```diff
-          store._push({ data: null, included: payload.included });
+          store._push({ data: [], included: payload.included });
```

However, `{ data: null }` is perfectly valid JSONAPI. In the [Top Level](http://jsonapi.org/format/#document-top-level) section of the JSONAPI spec:

> Primary data MUST be either:
>
> * a single resource object, a single resource identifier object, or null, for requests that target single resources
> * an array of resource objects, an array of resource identifier objects, or an empty array ([]), for requests that target resource collections

In the application where I found this issue, I was able to resolve this by creating a second monkey-patch ([my fix can be found here](https://github.com/amiel/emberfire-monkeypatch-issue/blob/initializer-hack/app/initializers/fix-emberfire-issue.js)).

However, my fix has some shortcomings. Specifically, since it is impossible to bypass a `_super` call and still call the original `_super`, this only works in my case because the relationship is already loaded and does not change.

I believe this could be resolved by changing the emberfire monkeypatch so that it ignores this specific case where `data` is `null`:

```javascript
var records = [];
if (Array.isArray(pushed)) {
  records = pushed.map(function(internalModel) {
    return internalModel.getRecord();
  });
} else if (pushed) {
  records = [pushed.getRecord()];
}
```

## Thank you

Thank you for both considering this fix, and for creating this ember addon in the first place. We have found it both extremely useful and a joy to work with :)

### PR DESCRIPTION
**Pull request by amiel**
This resolves #508.

Since the issue is related to using firebase adapter alongside other adapters within one Ember application, this change adds a new model to the test dummy app (a `widget` model), that uses `JSONAPIAdapter`.

The stub data is hard-coded in the adapter. I chose to do this over using something like ember-cli-mirage, as it doesn't seem like this project needs much more of this kind of thing and so ember-cli-mirage feels like overkill for the app. However, I'm happy to try a different approach to testing this if desired.

### CODE REVIEW

**Comment by amiel** [comment]
I signed it.

**Comment by amiel** [comment]
Hi, the test suite is passing locally for me. I'm not sure why it's failing on CI. It looks like an issue with npm...

**Comment by amiel** [comment]
UPDATE: It looks like the CI issue is resolved by using yarn instead of npm. ember-try uses yarn if yarn it is installed, and travis automatically installs yarn if a `yarn.lock` file is present. In my `EXPERIMENT` commit, I just added an empty yarn file. I'll drum up a new PR that adds a full `yarn.lock` file...

**Comment by amiel** [comment]
Thanks so much @jamesdaniels! Will there be a release so we can use the official version instead of our own branch?

**Comment by jamesdaniels** [comment]
We'll cut a release in the next couple days

**Comment by amiel** [comment]
Excellent. Thanks!

**Pull request merged**
