### PR TITLE
Add tests for #findQuery

### PR DESCRIPTION
**Pull request by halfdan**
* Adds simple integration tests for #findQuery 
* Querying not properly supported by mockfirebase
  * Can't really test the resulting recordArray
  * Can't test proper event handling

### CODE REVIEW

**Comment by halfdan** [comment]
PR'ing this so we can have a discussion about how to test this feature properly. Any ideas are welcome!

**Comment by halfdan** [comment]
Derp

**Comment by halfdan** [comment]
I signed it!

**Comment by tstirrat** [comment]
thanks for this, lets talk in the other pr

**Pull request merged**
