### PR TITLE
Fix firestore adapter reference options order

### LINKED ISSUE #611: Firestore adapter reference options order
- `options.endAt`, `options.endBefore`, `options.startAt` and `options.startAfter` should be applied after `options.orderBy`, not before
- Also, there is a typo in application of `options.startAfter`

### PR DESCRIPTION
**Pull request by maxymczech**
Fixes #611

### CODE REVIEW

**Comment by maxymczech** [comment]
@googlebot I signed it!

**Comment by maxymczech** [comment]
@googlebot I fixed it.

**Review by jamesdaniels — APPROVED** [review]
LGTM thanks

**Comment by maxymczech** [comment]
@jamesdaniels Hi, thank you  for accepting.. Does this mean you plan to continue working on `emberfire`?

**Comment by jamesdaniels** [comment]
Yes.

**Comment by maxymczech** [comment]
Thank you very much. I am working on a project running `emberfire@3`, I've forked it to fix some bugs, will check if I can contribute some other fixes.

**Comment by jamesdaniels** [comment]
That would be appreciated as I don't think any of us are actively using Ember ATM. So we lack the hands on experience.

**Pull request merged**
