### PR TITLE
JSON-API + new serializers

### PR DESCRIPTION
**Pull request by tstirrat**
Minimizes the footprint of code by using as much of the underlying `JSONSerializer` methods as possible.

The main point of difference between the inherited code is how `hasMany` relationships are stored.

Also uses `EmbeddedRecordsMixin` for embedded record processing. This will mean that setting the `embedded` option in the `models/*` files will be deprecated. The new way forward will be to use a per type serializer with `embedded: 'always'` as seen [here](http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html)

Merging #282 into this one while we iterate.

### CODE REVIEW

**Comment by tstirrat** [comment]
Even `2.0.0-canary` passes :white_check_mark: 

Just needs the embedded records stuff fixed up and we're good to go.

**Comment by tmayr** [comment]
Nice! I've tried looking at the embedded records but it goes way over my head, will keep looking!

**Comment by tstirrat** [comment]
I've decided to make new models specifically for the embedding, trying to override embedding stuff inside each test was too cryptic and problematic.

Should have something working by end of day :)

**Comment by tstirrat** [comment]
Waiting on emberjs/data#3550

**Comment by tmayr** [comment]
Oh wow, that was way more complex than I thought

**Comment by tstirrat** [comment]
Yeah, the way the new serializer stuff works you don't have access to the records anymore (it's for the best) .. but it sure made things a little crazy in the adapter :/

**Comment by tstirrat** [comment]
This will get us compatible with both 1.13.x and 2.0-canary

If you want to help out any more, we could do with some more testing to work out if there are any edge cases in the embedded records stuff. I have tested the "basic" example for embedded records, but there could be things like when there are relationships defined in both directions i.e. `parent hasMany children` where children define `child belongsTo parent`.

Or just check out this branch, pair it with branch in emberjs/data#3550 and try a few things out with it (not necessarily embedded stuff)

Tests in general will always be helpful in getting us over the line when 2.0 stable launches. Some of the new methods I wrote in the adapter need some checks and balances.

And finally I do want to eventually move the `recordWillDelete` code into the ember data standard `deleteRecord` handler.

**Comment by tstirrat** [comment]
Disabling embedded tests so that I can make an early release. the embedded stuff will need to wait for emberjs/data#3550

**Comment by tmayr** [comment]
Might give a try to updating to Ember Data 1.13 later using this branch, will let you know if everything goes smoothly.

**Pull request merged**
