### PR TITLE
Fix custom token support

### PR DESCRIPTION
**Pull request by IsaiahJTurner**
This has been tested and I can confirm it is working.

### CODE REVIEW

**Comment by IsaiahJTurner** [comment]
I signed it!

**Comment by IsaiahJTurner** [comment]
Oops! I'll rewrite those tests and remember to run tests next time.

**Comment by tstirrat** [comment]
```js
firebaseMock.authWithCustomToken.calledWith('token');
```

should be what you want

**Comment by tstirrat** [comment]
Moved to #307 and fixed the failing test.

**Pull request closed without merging**
