### PR TITLE
fix #480, use scheduleOnce instead of run

### LINKED ISSUE #480: Ember 2.11 : getting infinite rendering when loading a model with relationships
With Ember 2.11, when I load a relationships that have more than 10 elements, I get and "infinite rendering invalidation detected". 

This seems to come from adapters/firebase.js:142

```js
  _fetch(ref, log) {
    this._incrementWaiters();
    return new Promise((resolve, reject) => {

      ref.once('value', (snapshot) => {
        this._decrementWaiters();
        Ember.run(null, resolve, snapshot);

      }, (err) => {
        this._decrementWaiters();
        Ember.run(null, reject, err);
      });

    }, log);
  },
``` 

replacing by :

```js
  _fetch(ref, log) {
    this._incrementWaiters();
    return new Promise((resolve, reject) => {

      ref.once('value', (snapshot) => {
        this._decrementWaiters();
        Ember.run.scheduleOnce('afterRender', this, resolve, snapshot);

      }, (err) => {
        this._decrementWaiters();
        Ember.run.scheduleOnce('afterRender', this, reject, err);
      });

    }, log);
  },
``` 

works. I would guess it happens when we get a lot of update message at the same time, and they are called one after each other instead of being queued, anyway I will submit a pull request and you can see if you want to either fix the problem in firebase client or just fix it using ember.

### PR DESCRIPTION
**Pull request by olivierchatry**
### Description
Use scheduleOnce instead of firing as soon as we receive a value change message. Had to set ember-data to 2.10 for test to pass. This avoid entering in a long loop that make ember think we are infinite looping.

### CODE REVIEW

**Comment by tsubik** [comment]
@olivierchatry looks like this PR has introduced regression with acceptance tests, https://github.com/firebase/emberfire/issues/484. `scheduleOnce` relies on run loop autorun which is disabled in testing environment. We should find some other way to fix original issue cc @jamesdaniels

**Comment by olivierchatry** [comment]
Yep, seems like it, I'm not sure what to do there. And also, seems like emberfire is slowly dying :/

**Comment by olivierchatry** [comment]
Not sure if it is of any interest but : http://stackoverflow.com/questions/28746145/what-is-the-proper-way-in-ember-to-use-scheduleonce-that-is-test-friendly

**Comment by tsubik** [comment]
Wrapping in `Ember.run` could be a way, as normally if there is no open run loop it would create one, but does it resolve the original problem with Ember data. I would have to reproduce this problem.

**Comment by olivierchatry** [comment]
Hopefully it should, but I did not try.

**Comment by tsubik** [comment]
@olivierchatry do you have some repo to reproduce the original problem with infinite loop? I tried to reproduce that on my side project but without success.

**Comment by olivierchatry** [comment]
Nop, it happens multiple time on my software ( and made sense at this point
), but that was about 2 months ago. Is the Ember.run fix does not work for
you ?

**Comment by tsubik** [comment]
@olivierchatry I'm not an expert in run loop. I had to refresh my memory about it as I'm no longer working in Ember full-time :/, but I think just one `scheduleOnce` action does not make sense with `Ember.run` wrap. It should work the same way as just wrapping `resolve`, `reject` in simple `Ember.run`, which means simple revert of this PR will suffice. That's why I was asking about the repo to reproduce the original problem because I could be wrong :P. And yes, either wrap or revert to previous code solves problems with acceptance testing.

**Comment by olivierchatry** [comment]
I will remove the fix and try to reproduce the issue so that I can have a
clear answer. Should have done a unit test with the PR :(.

**Comment by tsubik** [comment]
Thanks @olivierchatry :+1:

**Comment by olivierchatry** [comment]
Yeah I was not able to reproduce the bug, but I did not try that hard either. Anyway, we can probably revert this PR if it a bother for a lot of people ( even if I think it is better to not fire up immediately the change ) .

**Comment by olivierchatry** [comment]
@jamesdaniels anyway you can do that ? and also maybe release a new version ?

**Comment by tsubik** [comment]
I've added PR for that :)

**Comment by jamesdaniels** [comment]
@olivierchatry done.

**Pull request merged**
