### PR TITLE
Update torii

### PR DESCRIPTION
**Pull request by oskarrough**
Updating Torii fixes some issues introduced with Ember 2.3.0 and gets rid of the `container` deprecation :palm_tree: 

- https://github.com/Vestorly/torii/issues/266
- https://github.com/Vestorly/torii/releases/tag/v0.8.0-beta.1

I've only tested it with our own Emberfire 1.6.6 application where it works fine but I see a failing test. Would be nice to get this update in.

### CODE REVIEW

**Comment by tstirrat** [comment]
I'm not very comfortable introducing a beta dependency :( What issues with 2.3.0 does it fix specifically?

We should encourage torii to make a point release with the container changes

**Comment by oskarrough** [comment]
Agree. We also ran into issues with the beta although I haven't had the opportunity to investigate further. The deprecation it fixes is Vestorly/torii#266.

Should probably also wait until https://github.com/Vestorly/torii/issues/287 is resolved.

**Comment by tstirrat** [comment]
Obsolete. 0.8.0 is now in master, will go out in emberfire 2.0

**Comment by oskarrough** [comment]
@tstirrat just updated to 2.0 and it seems there are still two "container deprecations":

https://github.com/firebase/emberfire/search?utf8=%E2%9C%93&q=application.container.lookupFactory

**Comment by tstirrat** [comment]
Thanks for the report, i tried to use `getOwner(app).resolveRegistration` but it broke in tests, will try to find out why when I get some time next week

**Pull request closed without merging**
