### PR TITLE
WIP Documented acceptance testing

### PR DESCRIPTION
**Pull request by binhums**
🚨  Do not merge, work in progress 🚨 

First steps towards setting up a standard practice for acceptance testing with EmberFire. This should include:

 - new docs including example test code, and
 - test helpers and blueprints that match existing ember acceptance testing patterns.

**Progress:**

- [x] Define an acceptance test module for Qunit, add to emberfire blueprint.
- [x] Add docs for standard approach including instructions for fixture data
- [x] Add module definition and example test for Mocha users.
- [ ] Add access to the firebase ref in the acceptance test
- [ ] Add instructions for handling changes to data, e.g. updates, additions, deletions
- [ ] Manually test example code with a basic ember app.

**Potentially out of scope:**

- [ ] Add acceptance tests to the dummy app
- [ ] Consider implications of trying to stub multiple Firebase instances.
- [ ] Updating Emberfire's acceptance tests to use the new module.

**Notable considerations:**

- ember-cli is [moving test helpers to individual test libraries](https://github.com/ember-cli/ember-cli-legacy-blueprints).

N.B. merging into branch `acceptance-testing`

cc @tstirrat

### CODE REVIEW

**Comment by binhums** [comment]
Related to #349

**Comment by villander** [comment]
Awesome @binhums 💃

**Comment by jemware** [comment]
+1

**Comment by tstirrat** [comment]
Going to squash and merge this into another branch to clean it up (CLA errors are due to my own email being misconfigured on github)

**Comment by tonycoco** [comment]
Any plan to add this? Also needed would be auth mocks.

**Comment by tpetrone** [comment]
Any updates?

**Pull request merged**
