### PR TITLE
Avoid infinite render on value change

### LINKED ISSUE #408: Does EmberFire support FirebaseUI Authentication?
I cannot seem to find it here or anywhere and it seems to be where AUTH is moving for hosted FB domains.

### LINKED ISSUE #480: Ember 2.11 : getting infinite rendering when loading a model with relationships
With Ember 2.11, when I load a relationships that have more than 10 elements, I get and "infinite rendering invalidation detected". 

This seems to come from adapters/firebase.js:142

```js
  _fetch(ref, log) {
    this._incrementWaiters();
    return new Promise((resolve, reject) => {

      ref.once('value', (snapshot) => {
        this._decrementWaiters();
        Ember.run(null, resolve, snapshot);

      }, (err) => {
        this._decrementWaiters();
        Ember.run(null, reject, err);
      });

    }, log);
  },
``` 

replacing by :

```js
  _fetch(ref, log) {
    this._incrementWaiters();
    return new Promise((resolve, reject) => {

      ref.once('value', (snapshot) => {
        this._decrementWaiters();
        Ember.run.scheduleOnce('afterRender', this, resolve, snapshot);

      }, (err) => {
        this._decrementWaiters();
        Ember.run.scheduleOnce('afterRender', this, reject, err);
      });

    }, log);
  },
``` 

works. I would guess it happens when we get a lot of update message at the same time, and they are called one after each other instead of being queued, anyway I will submit a pull request and you can see if you want to either fix the problem in firebase client or just fix it using ember.

### PR DESCRIPTION
**Pull request by steven-ferguson**
Fixes #480 . Looks like the issue was closed even though a fix was never merged.

### CODE REVIEW

**Comment by jamesdaniels** [comment]
We had to roll this back, due to #484. Any thoughts on how to fix the render + not break acceptance tests?

**Comment by steven-ferguson** [comment]
I had not seen that issue thanks for linking. One thing I am having trouble understanding is why just returning `ref.once('value')` as a promise from `_fetch` would not work:

```javascript
_fetch(ref) {
  return ref.once('value');
}
```

**Comment by steven-ferguson** [comment]
I have added a test which connects to a live firebase since that seems to be where the run loop issues were coming from. This test failed as expected with my initial commit, and now passes when only returning the promise from `ref.once('value')`.

**Comment by steven-ferguson** [comment]
Ok updated. Let me know if you want to squash this down to one commit.

**Comment by jamesdaniels** [comment]
We can squash from the pull request. Tests are red though @steven-ferguson can you take a peek?

**Comment by steven-ferguson** [comment]
I was not able to reproduce the failures on my local machine. Would you mind kicking the build off again?

**Comment by tstirrat** [comment]
I kicked it off again, let's see how that goes.

**Comment by tstirrat** [comment]
Pushing out a release, btw.

**Pull request merged**
