### PR TITLE
Ember Data 15+ compatibility

### PR DESCRIPTION
**Pull request by tstirrat**
- Includes some general test cleanup
  - Every test does a full setup and teardown cycle, this *should* make all tests atomic (no shared state or required running order)
  - Moved enqueue tests into unit tests and reduced execution time
  - Renamed all integration test filenames so that they match the title shown in mocha
  - adapters are not singletons anymore so needed to use `store.adapterFor` instead of `container.lookup('adapter:x')` emberjs/data#2915
- Passes on 15, 16.1 (and canary!)
- `_getRef` now takes type as either a `string` or a `class`, closes #141 

@brendanoh @MattMSumner please help test :)

### CODE REVIEW

**Comment by brendanoh** [comment]
@tstirrat @sararob I will upgrade a Pai.rs branch to this version today as well as to ED Canary and see what works. 

If I have issues will revert to beta 16.1, then 15 etc.

**Comment by brendanoh** [comment]
Well currently on Ember 1.11 and ED beta 16.1 all is well. Tried Ember canary originally and this was a problem: https://github.com/emberjs/data/issues/2967 Thankfully it is fixed by https://github.com/emberjs/data/pull/2959 but didn't try ED canary yet but will. 

Live by canary. Die by canary.

**Comment by sararob** [comment]
@tstirrat I tested in the blog demo and everything looks good to me! Nice work.

**Comment by tstirrat** [comment]
Great!! I also tried it on a local pairs app.. no ghosting problem either. perhaps that was only in `beta.14.1`...

**Comment by oskarrough** [comment]
Hey, would like to help test this. How do I use this version of Emberfire, preferably through bower?

**Comment by MattMSumner** [comment]
@oskarrough you can add the following to you `devDependencies` in package.json:
```js
    "emberfire": "git://github.com/firebase/emberfire#ts-ed-beta-16-compat",
```

**Comment by h55nick** [comment]
:+1:

**Pull request merged**
